In [0]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten,Dense

In [4]:
print(tf.__version__)

2.2.0-rc4

In [0]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split

In [0]:
dataset = pd.read_csv(r"/content/drive/My Drive/Colab Notebooks/Data Folder/Churn_Modelling.csv")

In [8]:
dataset.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
X = dataset.drop(labels=['CustomerId','Surname','RowNumber','Exited'],axis=1)
y = dataset['Exited']

In [11]:
X.head()

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [12]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [0]:
from sklearn.preprocessing import LabelEncoder

In [14]:
# Converting Categorical Data to Numerical Data
label1 = LabelEncoder()
X['Geography'] = label1.fit_transform(X['Geography'])
X.head()

   CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [15]:
# Converting Categorical Data to Numerical Data
label2 = LabelEncoder()
X['Gender'] = label2.fit_transform(X['Gender'])
X.head()

   CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [16]:
X = pd.get_dummies(X,drop_first=True,columns=['Geography']) # no Geography_3 (redundant)
X.head()

   CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1

[5 rows x 11 columns]

# Feature Standardization

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2 ,random_state = 0 , stratify = y )

In [0]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [22]:
X_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

# Build ANN

In [0]:
model = Sequential()
model.add(Dense(X.shape[1],activation="relu",input_dim = X.shape[1]))
model.add(Dense(128,activation="relu"))
model.add(Dense(1,activation="sigmoid"))

In [29]:
X.shape[1]

11

In [0]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [34]:
# converting y_train from pandas series to numpy array
# Stochastic gradient Descent becomes Batch gradient descent
model.fit(X_train,y_train.to_numpy(),batch_size=10,epochs=10,verbose =1)

Epoch 1/10
800/800 [==============================] - 1s 1ms/step - loss: 0.4572 - accuracy: 0.8002
Epoch 2/10
800/800 [==============================] - 1s 1ms/step - loss: 0.4036 - accuracy: 0.8279
Epoch 3/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3714 - accuracy: 0.8443
Epoch 4/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3581 - accuracy: 0.8496
Epoch 5/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3505 - accuracy: 0.8581
Epoch 6/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3452 - accuracy: 0.8571
Epoch 7/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3415 - accuracy: 0.8609
Epoch 8/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3374 - accuracy: 0.8630
Epoch 9/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3330 - accuracy: 0.8637
Epoch 10/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3324 - accuracy: 0.8644

In [35]:
# Trying with more epochs
model = Sequential()
model.add(Dense(X.shape[1],activation="relu",input_dim = X.shape[1]))
model.add(Dense(128,activation="relu"))
model.add(Dense(1,activation="sigmoid"))
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
model.fit(X_train,y_train.to_numpy(),batch_size=10,epochs=20,verbose =1)

Epoch 1/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4543 - accuracy: 0.8080
Epoch 2/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3899 - accuracy: 0.8388
Epoch 3/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3608 - accuracy: 0.8514
Epoch 4/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3486 - accuracy: 0.8590
Epoch 5/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3434 - accuracy: 0.8605
Epoch 6/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3389 - accuracy: 0.8634
Epoch 7/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3354 - accuracy: 0.8627
Epoch 8/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3335 - accuracy: 0.8633
Epoch 9/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3311 - accuracy: 0.8615
Epoch 10/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3303 - accuracy: 0.8640
Epoch 11/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3284 - accuracy: 0.8630
Epoch 12/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3265 - accuracy: 0.8636
Epoch 13/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3269 - accuracy: 0.8649
Epoch 14/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3249 - accuracy: 0.8668
Epoch 15/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3244 - accuracy: 0.8665
Epoch 16/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3229 - accuracy: 0.8646
Epoch 17/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3224 - accuracy: 0.8659
Epoch 18/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3209 - accuracy: 0.8680
Epoch 19/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3219 - accuracy: 0.8695
Epoch 20/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3210 - accuracy: 0.8652

In [36]:
y_pred = model.predict_classes(X_test)

WARNING:tensorflow:From <ipython-input-36-fdaaf2360398>:1: Sequential.predict_classes (from tensorflow.python.keras.engine.sequential) is deprecated and will be removed after 2021-01-01.
Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).

In [37]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int32)

In [38]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [39]:
model.evaluate(X_test,y_test.to_numpy())

63/63 [==============================] - 0s 1ms/step - loss: 0.3499 - accuracy: 0.8565

[0.34994181990623474, 0.8565000295639038]

In [0]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [41]:
confusion_matrix(y_test,y_pred)

array([[1522,   71],
       [ 216,  191]])

In [42]:
accuracy_score(y_test,y_pred)

0.8565